---
# check rust (after install update PATH)
- name: Setup local workstation
  hosts: local
  roles:
      - role: zsh
        tags:
            - zsh
      - role: apt
        tags:
            - apt
      - role: pip
        tags:
            - pip
      - role: rust
        tags:
            - rust
      - role: alacritty
        tags:
            - alacritty
      - role: desktop
        tags:
            - desktop
      - role: fonts
        tags:
            - fonts
      - role: telegram
        tags:
            - telegram
  tags:
      - local

- name: Setup remote servers
  hosts: servers
  roles:
      - role: zsh
        tags:
            - zsh
      - role: apt
        tags:
            - apt
      - role: pip
        tags:
            - pip
  tags:
      - never
      - servers
