---

dependencies:
    - cmake
    - pkg-config
    - libfreetype6-dev
    - libfontconfig1-dev
    - libxcb-xfixes0-dev
    - libxkbcommon-dev
    - python3
    - desktop-file-utils

repository: "https://github.com/alacritty/alacritty.git"
