---

- name: Install dependencies
  apt:
    name: "{{item}}"
    update_cache: yes
  loop: "{{dependencies}}"
  become: yes

- name: Create build dir
  tempfile:
    state: directory
    prefix: alacritty
    suffix: build
  register: build_dir

- name: Clone "{{repository}}"
  git:
    repo: "{{repository}}"
    dest: "{{build_dir.path}}"

- name: Build alacritty
  command: ~/.cargo/bin/cargo build --release
  args:
    chdir: "{{build_dir.path}}"

- name: Install alacritty terminfo globally
  command: tic -xe alacritty,alacritty-direct extra/alacritty.info
  args:
    chdir: "{{build_dir.path}}"
  become: yes

- name: Configure desktop entries
  shell: 
    cmd: >
      cp target/release/alacritty /usr/local/bin &&
      cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg &&
      desktop-file-install extra/linux/Alacritty.desktop &&
      update-desktop-database
  args:
    chdir: "{{build_dir.path}}"
  become: yes
